# Config for https://github.com/toolmantim/release-drafter
name-template: 'MyProject28 $NEXT_PATCH_VERSION'
tag-template: '$NEXT_PATCH_VERSION'
#filter-by-commitish: true
commitish: 2.8.x

change-template: '- $TITLE [#$NUMBER] by [@$AUTHOR](https://github.com/$AUTHOR)'
template: |
  ## Changes_28x/28x

  $CHANGES
